version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  # surrealdb:
  #   image: surrealdb/surrealdb:latest
  #   container_name: surrealdb
  #   ports:
  #     - 8000:8000
  #   command:
  #     - start
  #     - --log=trace
  #     - --user=root
  #     - --pass=root
  #     # - tikv://pd0:2379
  #   # depends_on:
  #   #   - tikv0
  #   #   - tikv1
  #   #   - tikv2
  #   restart: always
  #   networks:
  #     - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
